name: riverpod_ddd
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: packages/api_client
  app_ui:
    path: packages/app_ui   
  app_utils:
    path: packages/app_utils
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  # flutter_easylogger: ^2.3.3
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  get_it: ^7.6.4
  go_router: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^4.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
    - assets/images/



